import { v4 as uuidv4 } from "uuid";
export interface FamilyMember {
  name: string;
  image: string;
  color: string;
  _id: string;
  children?: FamilyMember[];
}

//if no doc for the name; id = uuidv4()
export const members: FamilyMember[] = [
  {
    name: "Okonkwo Ndichie Omile",
    _id: "678b99fa87c1224c80dbce67",
    image: "",
    color: "",
    children: [
      // MUO NDICHIE OMILE
      {
        name: "Muo Ndichie Omile",
        _id: "678ba753f0da3723bf62162b",
        image: "",
        color: "#7C0902",
        children: [
          {
            name: "Mgbankwo Ezebilo",
            _id: "678bad9f4ee74cfa3fc94a56",
            image: "",
            color: "#7C0902",
            children: [
              {
                name: "Elizabeth Ejindu",
                _id: "678bbb454ee74cfa3fc94b00",
                image: "",
                color: "#7C0902",
                children: [],
              },
              {
                name: "Vincent Ezebilo",
                _id: "678bbbea4ee74cfa3fc94b0a",
                image: "",
                color: "#7C0902",
                children: [],
              },
              {
                name: "Ngozi Enwelani",
                _id: uuidv4(),
                image: "",
                color: "#7C0902",
                children: [],
              },
            ],
          },
          {
            name: "Ichie Gabriel Omile",
            _id: "678bb0864ee74cfa3fc94a60",
            image: "",
            color: "#7C0902",
            children: [
              {
                name: "Nkeiruka Egwudike",
                _id: uuidv4(),
                image: "",
                color: "#7C0902",
                children: [
                  {
                    name: "Chioma Egwudike",
                    _id: uuidv4(),
                    image: "",
                    color: "#7C0902",
                    children: [],
                  },
                  {
                    name: "Chisom Egwudike",
                    _id: uuidv4(),
                    image: "",
                    color: "#7C0902",
                    children: [],
                  },
                  {
                    name: "Ifeanyi Egwudike",
                    _id: uuidv4(),
                    image: "",
                    color: "#7C0902",
                    children: [],
                  },
                  {
                    name: "Onyekachukwu Egwudike",
                    _id: uuidv4(),
                    image: "",
                    color: "#7C0902",
                    children: [],
                  },
                  {
                    name: "Obinna Egwudike",
                    _id: uuidv4(),
                    image: "",
                    color: "#7C0902",
                    children: [],
                  },
                ],
              },
              {
                name: "Engr. Chijioke Omile",
                _id: "678bb6304ee74cfa3fc94aac",
                image: "",
                color: "#7C0902",
                children: [
                  {
                    name: "Chibueze Omile",
                    _id: uuidv4(),
                    image: "",
                    color: "#7C0902",
                    children: [],
                  },
                  {
                    name: "Chinaza Omile",
                    _id: uuidv4(),
                    image: "",
                    color: "#7C0902",
                    children: [],
                  },
                  {
                    name: "Chioma Omile",
                    _id: uuidv4(),
                    image: "",
                    color: "#7C0902",
                    children: [],
                  },
                  {
                    name: "Kenechukwu Omile",
                    _id: uuidv4(),
                    image: "",
                    color: "#7C0902",
                    children: [],
                  },
                ],
              },
              {
                name: "Dr. Chukwudi Omile",
                _id: "678bb6904ee74cfa3fc94ab1",
                image: "",
                color: "#7C0902",
                children: [
                  {
                    name: "Tobenna Omile",
                    image: "",
                    _id: uuidv4(),
                    color: "#7C0902",
                    children: [],
                  },
                  {
                    name: "Chukwuebuka Omile",
                    _id: uuidv4(),
                    image: "",
                    color: "#7C0902",
                    children: [],
                  },
                ],
              },
              {
                name: "Nnaedozie Omile",
                _id: "678bb6da4ee74cfa3fc94ab7",
                image: "",
                color: "#7C0902",
                children: [
                  {
                    name: "Izuchukwu Omile",
                    _id: uuidv4(),
                    image: "",
                    color: "#7C0902",
                    children: [],
                  },
                  {
                    name: "Chimaobi Omile",
                    _id: uuidv4(),
                    image: "",
                    color: "#7C0902",
                    children: [],
                  },
                  {
                    name: "Chiagozie Omile",
                    _id: uuidv4(),
                    image: "",
                    color: "#7C0902",
                    children: [],
                  },
                ],
              },

              {
                name: "Uzoamaka Ezumoha",
                _id: "678bb76b4ee74cfa3fc94ac1",
                image: "",
                color: "#7C0902",
                children: [
                  {
                    name: "Chimamanda Ezumoha",
                    _id: uuidv4(),
                    image: "",
                    color: "#7C0902",
                    children: [],
                  },
                ],
              },
              {
                name: "Engr. Uchenna Omile",
                _id: "678bb7284ee74cfa3fc94abd",
                image: "",
                color: "#7C0902",
                children: [
                  {
                    name: "Olisaemeka Omile",
                    _id: uuidv4(),
                    image: "",
                    color: "#7C0902",
                    children: [],
                  },
                  {
                    name: "Kamsicho Omile",
                    _id: uuidv4(),
                    image: "",
                    color: "#7C0902",
                    children: [],
                  },
                  {
                    name: "Munachi Omile",
                    _id: uuidv4(),
                    image: "",
                    color: "#7C0902",
                    children: [],
                  },
                ],
              },
              {
                name: "Adaobi Obasi",
                _id: "678bb7c74ee74cfa3fc94ac8",
                image: "",
                color: "#7C0902",
                children: [
                  {
                    name: "Ifeatu Obasi",
                    _id: uuidv4(),
                    image: "",
                    color: "#7C0902",
                    children: [],
                  },
                  {
                    name: "Onamma Obasi",
                    _id: uuidv4(),
                    image: "",
                    color: "#7C0902",
                    children: [],
                  },
                  {
                    name: "Kaosolu Obasi",
                    _id: uuidv4(),
                    image: "",
                    color: "#7C0902",
                    children: [],
                  },
                  {
                    name: "Uchechukwu Obasi",
                    _id: uuidv4(),
                    image: "",
                    color: "#7C0902",
                    children: [],
                  },
                ],
              },
            ],
          },
          {
            name: "Justina Ifezue",
            _id: "678bb11b4ee74cfa3fc94a6a",
            image: "",
            color: "#7C0902",
            children: [
              {
                name: "Innocent Ifezue",
                _id: "678bba264ee74cfa3fc94ae7",
                image: "",
                color: "#7C0902",
                children: [
                  {
                    name: "Chukwu Ifezue",
                    _id: uuidv4(),
                    image: "",
                    color: "#7C0902",
                    children: [],
                  },
                  {
                    name: "Onyedika Ifezue",
                    _id: uuidv4(),
                    image: "",
                    color: "#7C0902",
                    children: [],
                  },
                  {
                    name: "Somtochukwu Ifezue",
                    _id: uuidv4(),
                    image: "",
                    color: "#7C0902",
                    children: [],
                  },
                  {
                    name: "Otitodilinna Alfred Ifezue",
                    _id: uuidv4(),
                    image: "",
                    color: "#7C0902",
                    children: [],
                  },
                ],
              },
              {
                name: "Paul Ifezue",
                _id: "678bba7e4ee74cfa3fc94aef",
                image: "",
                color: "#7C0902",
                children: [
                  {
                    name: "Cynthia Ifezue",
                    _id: uuidv4(),
                    image: "",
                    color: "#7C0902",
                    children: [],
                  },
                  {
                    name: "Franklin Ifezue",
                    _id: uuidv4(),
                    image: "",
                    color: "#7C0902",
                    children: [],
                  },
                  {
                    name: "Merilyn Ifezue",
                    _id: uuidv4(),
                    image: "",
                    color: "#7C0902",
                    children: [],
                  },
                  {
                    name: "Chiemelie Ifezue",
                    _id: uuidv4(),
                    image: "",
                    color: "#7C0902",
                    children: [],
                  },
                  {
                    name: "Dorothy Ifezue",
                    _id: uuidv4(),
                    image: "",
                    color: "#7C0902",
                    children: [],
                  },
                ],
              },
              {
                name: "Paulinus Ifezue",
                _id: "678bbaaa4ee74cfa3fc94af4",
                image: "",
                color: "#7C0902",
                children: [
                  {
                    name: "Chidera Ifezue",
                    _id: uuidv4(),
                    image: "",
                    color: "#7C0902",
                    children: [],
                  },
                  {
                    name: "Chiamaka Ifezue",
                    _id: uuidv4(),
                    image: "",
                    color: "#7C0902",
                    children: [],
                  },
                ],
              },
              {
                name: "Ngozi Ifezue",
                _id: "678bb11b4ee74cfa3fc94a66",
                image: "",
                color: "#7C0902",
                children: [],
              },
              {
                name: "Agatha Ifezue",
                _id: "678bb11b4ee74cfa3fc94a67",
                image: "",
                color: "#7C0902",
                children: [],
              },
              {
                name: "Chika Ajibuogu",
                _id: "678bbae04ee74cfa3fc94af8",
                image: "",
                color: "#7C0902",
                children: [
                  {
                    name: "Oluchi Ajigbogu",
                    _id: uuidv4(),
                    image: "",
                    color: "#7C0902",
                    children: [],
                  },
                ],
              },
              {
                name: "Chinedu Ifezue",
                _id: "678bbb094ee74cfa3fc94afc",
                image: "",
                color: "#7C0902",
                children: [
                  {
                    name: "Chinelo Ifezue",
                    _id: uuidv4(),
                    image: "",
                    color: "#7C0902",
                    children: [],
                  },
                ],
              },
            ],
          },
          {
            name: "Francis Nwafor Omile",
            _id: "678bb24c4ee74cfa3fc94a76",
            image: "",
            color: "#7C0902",
            children: [
              {
                name: "Francisca Ifemkwe",
                _id: uuidv4(),
                image: "",
                color: "#7C0902",
                children: [],
              },
              {
                name: "Okechukwu Omile",
                _id: "678bb9444ee74cfa3fc94adb",
                image: "",
                color: "#7C0902",
                children: [
                  {
                    name: "Nonimechi Omile",
                    _id: uuidv4(),
                    image: "",
                    color: "#7C0902",
                    children: [],
                  },
                  {
                    name: "Nesochukwu Omile",
                    _id: uuidv4(),
                    image: "",
                    color: "#7C0902",
                    children: [],
                  },
                ],
              },
              {
                name: "Anayo Omile",
                _id: uuidv4(),
                image: "",
                color: "#7C0902",
                children: [],
              },
              {
                name: "Chikwendu Omile",
                _id: uuidv4(),
                image: "",
                color: "#7C0902",
                children: [],
              },
            ],
          },
          {
            name: "Chukwuemeka Omile",
            _id: "678bb1854ee74cfa3fc94a6f",
            image: "",
            color: "#7C0902",
            children: [
              {
                name: "Nnaemeka Omile",
                _id: "678bb9a04ee74cfa3fc94ae0",
                image: "",
                color: "#7C0902",
                children: [
                  {
                    name: "Amarachi Clara Omile",
                    _id: uuidv4(),
                    image: "",
                    color: "#7C0902",
                    children: [],
                  },
                  {
                    name: "Chidera Olivia Omile",
                    _id: uuidv4(),
                    image: "",
                    color: "#7C0902",
                    children: [],
                  },
                ],
              },
              {
                name: "Ogechukwu Omile",
                _id: uuidv4(),
                image: "",
                color: "#7C0902",
                children: [],
              },
            ],
          },
          {
            name: "Cecilia Okoro",
            _id: "678bb29b4ee74cfa3fc94a7b",
            image: "",
            color: "#7C0902",
            children: [
              {
                name: "Dr. Kenechukwu Okoro",
                _id: "678bb8464ee74cfa3fc94ace",
                image: "",
                color: "#7C0902",
                children: [
                  {
                    name: "Oluchukwu Okoro",
                    _id: uuidv4(),
                    image: "",
                    color: "#7C0902",
                    children: [],
                  },
                  {
                    name: "Adachukwu Okoro",
                    _id: uuidv4(),
                    image: "",
                    color: "#7C0902",
                    children: [],
                  },
                  {
                    name: "Okechukwu Anthony Okoro",
                    _id: uuidv4(),
                    image: "",
                    color: "#7C0902",
                    children: [],
                  },
                ],
              },
              {
                name: "Bar Tobechukwu Okoro",
                _id: "678bb8a64ee74cfa3fc94ad3",
                image: "",
                color: "#7C0902",
                children: [
                  {
                    name: "Onyekachukwu Okoro",
                    _id: uuidv4(),
                    image: "",
                    color: "#7C0902",
                    children: [],
                  },
                  {
                    name: "Onyinye Okoro",
                    _id: uuidv4(),
                    image: "",
                    color: "#7C0902",
                    children: [],
                  },
                ],
              },
            ],
          },
          {
            name: "Juliana Ngene",
            _id: "678bb35a4ee74cfa3fc94a86",
            image: "",
            color: "#7C0902",
            children: [
              {
                name: "Onyinyechukwu Omile",
                _id: uuidv4(),
                image: "",
                color: "#7C0902",
                children: [],
              },
            ],
          },
          {
            name: "Chigolum Omile",
            _id: "678bb3064ee74cfa3fc94a82",
            image: "",
            color: "#7C0902",
            children: [
              {
                name: "Kosisochukwu Omile",
                _id: uuidv4(),
                image: "",
                color: "#7C0902",
                children: [],
              },
              {
                name: "Adaeze Udeh",
                _id: uuidv4(),
                image: "",
                color: "#7C0902",
                children: [],
              },
              {
                name: "Ejike Omile",
                _id: "678bbce04ee74cfa3fc94b10",
                image: "",
                color: "#7C0902",
                children: [
                  {
                    name: "Kaosisochukwu Omile",
                    _id: uuidv4(),
                    image: "",
                    color: "#7C0902",
                    children: [],
                  },
                  {
                    name: "Onyedikachukwu Omile",
                    _id: uuidv4(),
                    image: "",
                    color: "#7C0902",
                    children: [],
                  },
                ],
              },
              {
                name: "Dr Chikelue Omile",
                _id: "678bbd024ee74cfa3fc94b14",
                image: "",
                color: "#7C0902",
                children: [
                  {
                    name: "Somtochukwu Omile",
                    _id: uuidv4(),
                    image: "",
                    color: "#7C0902",
                    children: [],
                  },
                ],
              },
            ],
          },
          {
            name: "Nkechi Ogbuoji",
            _id: "678bb3c54ee74cfa3fc94a8d",
            image: "",
            color: "#7C0902",
            children: [
              {
                name: "Emeka Ogbuoji",
                _id: uuidv4(),
                image: "",
                color: "#7C0902",
                children: [],
              },
              {
                name: "Ifeoma Ogbuoji",
                _id: uuidv4(),
                image: "",
                color: "#7C0902",
                children: [],
              },
              {
                name: "Uchenna Ogbuoji",
                _id: uuidv4(),
                image: "",
                color: "#7C0902",
                children: [],
              },
              {
                name: "Nkeiru Ogbuoji",
                _id: uuidv4(),
                image: "",
                color: "#7C0902",
                children: [],
              },
            ],
          },
          {
            name: "Obianuju Okekemekam",
            _id: "678bb4234ee74cfa3fc94a91",
            image: "",
            color: "#7C0902",
            children: [
              {
                name: "Uchenna Okeke",
                _id: uuidv4(),
                image: "",
                color: "#7C0902",
                children: [],
              },
            ],
          },
          {
            name: "Ezimma Omile",
            _id: uuidv4(),
            image: "",
            color: "#7C0902",
            children: [],
          },
          {
            name: "Mmaduka Omile",
            _id: "678bb4bb4ee74cfa3fc94a98",
            image: "",
            color: "#7C0902",
            children: [
              {
                name: "Onyinye Omile",
                _id: uuidv4(),
                image: "",
                color: "#7C0902",
                children: [],
              },
              {
                name: "Chizubelu Omile",
                _id: uuidv4(),
                image: "",
                color: "#7C0902",
                children: [],
              },
              {
                name: "Chibuike Omile",
                _id: uuidv4(),
                image: "",
                color: "#7C0902",
                children: [],
              },
              {
                name: "Ugochukwu Omile",
                _id: uuidv4(),
                image: "",
                color: "#7C0902",
                children: [],
              },
            ],
          },
          {
            name: "Ikechukwu Omile",
            _id: "678bc3fb4ee74cfa3fc94b57",
            image: "",
            color: "#7C0902",
            children: [
              {
                name: "Chinonyelum Omile",
                _id: uuidv4(),
                image: "",
                color: "#7C0902",
                children: [],
              },
              {
                name: "Nnedimma Omile",
                _id: uuidv4(),
                image: "",
                color: "#7C0902",
                children: [],
              },
              {
                name: "Chidimma Omile",
                _id: uuidv4(),
                image: "",
                color: "#7C0902",
                children: [],
              },
              {
                name: "Kenennna Omile",
                _id: uuidv4(),
                image: "",
                color: "#7C0902",
                children: [],
              },
            ],
          },
          {
            name: "Nduka Omile",
            _id: "678bb52d4ee74cfa3fc94a9d",
            image: "",
            color: "#7C0902",
            children: [
              {
                name: "Chidera Omile",
                _id: uuidv4(),
                image: "",
                color: "#7C0902",
                children: [],
              },
              {
                name: "Prisca Chiemegoun Omile",
                _id: uuidv4(),
                image: "",
                color: "#7C0902",
                children: [],
              },
            ],
          },
        ],
      },

      // JOACHIM IBEACHUZINAM
      {
        name: "Joachim Ibeachuzinam Omile",
        _id: "678ba7f7f0da3723bf62162e",
        image: "",
        color: "#007FFF",
        children: [
          {
            name: "Chinwemma Madike",
            _id: "678bbffc4ee74cfa3fc94b2c",
            image: "",
            color: "#007FFF",
            children: [
              {
                name: "Okwuchukwu Madike",
                _id: uuidv4(),
                image: "",
                color: "#007FFF",
                children: [],
              },
              {
                name: "Nkiruka Madike",
                _id: uuidv4(),
                image: "",
                color: "#007FFF",
                children: [],
              },
              {
                name: "Ginika Odezue",
                _id: uuidv4(),
                image: "",
                color: "#007FFF",
                children: [],
              },
            ],
          },
          {
            name: "Ndubuisi Omile",
            _id: "678bc0d64ee74cfa3fc94b35",
            image: "",
            color: "#007FFF",
            children: [
              {
                name: "Ogochukwu Udekene",
                _id: "678bc51f4ee74cfa3fc94b68",
                image: "",
                color: "#007FFF",
                children: [
                  {
                    name: "Kaosisochukwu Udekene",
                    _id: uuidv4(),
                    image: "",
                    color: "#007FFF",
                    children: [],
                  },
                  {
                    name: "Chidera Udekene",
                    _id: uuidv4(),
                    image: "",
                    color: "#007FFF",
                    children: [],
                  },
                  {
                    name: "Chimdindu Udekene",
                    _id: uuidv4(),
                    image: "",
                    color: "#007FFF",
                    children: [],
                  },
                  {
                    name: "Ogochukwu Udekene",
                    _id: uuidv4(),
                    image: "",
                    color: "#007FFF",
                    children: [],
                  },
                  {
                    name: "Chidimma Udekene",
                    _id: uuidv4(),
                    image: "",
                    color: "#007FFF",
                    children: [],
                  },
                  {
                    name: "Chinaecherem Udekene",
                    _id: uuidv4(),
                    image: "",
                    color: "#007FFF",
                    children: [],
                  },
                  {
                    name: "Isochukwuamaka Udekene",
                    _id: uuidv4(),
                    image: "",
                    color: "#007FFF",
                    children: [],
                  },
                ],
              },
              {
                name: "Njideka Omile",
                _id: uuidv4(),
                image: "",
                color: "#007FFF",
                children: [],
              },
              {
                name: "Magnus Omile",
                _id: uuidv4(),
                image: "",
                color: "#007FFF",
                children: [],
              },
              {
                name: "Thelma Edacha",
                _id: uuidv4(),
                image: "",
                color: "#007FFF",
                children: [],
              },
              {
                name: "Chukwujekwu Omile",
                _id: uuidv4(),
                image: "",
                color: "#007FFF",
                children: [],
              },
              {
                name: "Winifred Okeke",
                _id: "678bc5da4ee74cfa3fc94b72",
                image: "",
                color: "#007FFF",
                children: [],
              },
            ],
          },
          {
            name: "Dr. Ibeachuzinam Omile",
            _id: "678bc27e4ee74cfa3fc94b43",
            image: "",
            color: "#007FFF",
            children: [
              {
                name: "Chizaram Omile",
                _id: uuidv4(),
                image: "",
                color: "#007FFF",
                children: [],
              },
            ],
          },
          {
            name: "Nkechi Omile",
            _id: uuidv4(),
            image: "",
            color: "#007FFF",
            children: [],
          },
          {
            name: "Uche Nchikwo",
            _id: uuidv4(),
            image: "",
            color: "#007FFF",
            children: [],
          },
          {
            name: "Ikechukwu Omile",
            _id: uuidv4(),
            image: "",
            color: "#007FFF",
            children: [],
          },
          {
            name: "Chukwudi Omile",
            _id: uuidv4(),
            image: "",
            color: "#007FFF",
            children: [],
          },
          {
            name: "Ann Obiekwe",
            _id: "678bc19c4ee74cfa3fc94b3f",
            image: "",
            color: "#007FFF",
            children: [
              {
                name: "Franka Ndigwe",
                _id: uuidv4(),
                image: "",
                color: "#007FFF",
                children: [],
              },
              {
                name: "Ndukwe Obiekwe",
                _id: uuidv4(),
                image: "",
                color: "#007FFF",
                children: [],
              },
              {
                name: "Anthony Obiekwe",
                _id: uuidv4(),
                image: "",
                color: "#007FFF",
                children: [],
              },
              {
                name: "Jude Obiekwe",
                _id: uuidv4(),
                image: "",
                color: "#007FFF",
                children: [],
              },
              {
                name: "Nkiru Obiekwe",
                _id: uuidv4(),
                image: "",
                color: "#007FFF",
                children: [],
              },
              {
                name: "Udoka Obiekwe",
                _id: uuidv4(),
                image: "",
                color: "#007FFF",
                children: [],
              },
              {
                name: "Ifeatu Obiekwe",
                _id: uuidv4(),
                image: "",
                color: "#007FFF",
                children: [],
              },
            ],
          },
          {
            name: "Polycap Omile",
            _id: "678bc3084ee74cfa3fc94b4b",
            image: "",
            color: "#007FFF",
            children: [
              {
                name: "Jennifer Omile",
                _id: uuidv4(),
                image: "",
                color: "#007FFF",
                children: [],
              },
              {
                name: "Omile Pascal",
                _id: uuidv4(),
                image: "",
                color: "#007FFF",
                children: [],
              },
              {
                name: "Collins Omile",
                _id: uuidv4(),
                image: "",
                color: "#007FFF",
                children: [],
              },
              {
                name: "Victor Omile",
                _id: uuidv4(),
                image: "",
                color: "#007FFF",
                children: [],
              },
              {
                name: "Flourish Omile",
                _id: uuidv4(),
                image: "",
                color: "#007FFF",
                children: [],
              },
            ],
          },
        ],
      },

      // Benjamin Orakwute (Okpokora)
      {
        name: "Benjamin Orakwute (Okpokora)",
        _id: "678ba855f0da3723bf621631",
        image: "",
        color: "#004225",
        children: [],
      },

      // Mgbafor Ikeli (nee omile)
      {
        name: "Mgbafor Ikeli (Nee omile)",
        _id: "678c5db3692c5f6ca81f7fd3",
        image: "",
        color: "#FF0090",
        children: [
          {
            name: "Mgbafocha Oforah",
            _id: "678c5e89692c5f6ca81f7fd9",
            image: "",
            color: "#FF0090",
            children: [
              {
                name: "Rose Oforah",
                _id: uuidv4(),
                image: "",
                color: "#FF0090",
                children: [],
              },
              {
                name: "Johnny Oforah",
                _id: uuidv4(),
                image: "",
                color: "#FF0090",
                children: [],
              },
              {
                name: "Ogechukwu Oguno",
                _id: "678c5fb7692c5f6ca81f7fe7",
                image: "",
                color: "#FF0090",
                children: [
                  {
                    name: "Ozioma Oguno",
                    _id: uuidv4(),
                    image: "",
                    color: "#FF0090",
                    children: [],
                  },
                  {
                    name: "Mmesoma Oguno",
                    _id: uuidv4(),
                    image: "",
                    color: "#FF0090",
                    children: [],
                  },
                ],
              },
            ],
          },
          {
            name: "Chinweike Okolodibe",
            _id: uuidv4(),
            image: "",
            color: "#FF0090",
            children: [],
          },
          {
            name: "Chinedu Ikeli",
            _id: uuidv4(),
            image: "",
            color: "#FF0090",
            children: [],
          },
          {
            name: "Igwego Ike",
            _id: "678c6531692c5f6ca81f8020",
            image: "",
            color: "#FF0090",
            children: [
              {
                name: "Remigus Ike",
                _id: "678c65a2692c5f6ca81f8026",
                image: "",
                color: "#FF0090",
                children: [
                  {
                    name: "Chimaeme Ike",
                    _id: uuidv4(),
                    image: "",
                    color: "#FF0090",
                    children: [],
                  },
                  {
                    name: "Kosisochukwu Ike",
                    _id: uuidv4(),
                    image: "",
                    color: "#FF0090",
                    children: [],
                  },
                  {
                    name: "Kamsiyo Ike",
                    _id: uuidv4(),
                    image: "",
                    color: "#FF0090",
                    children: [],
                  },
                ],
              },
              {
                name: "Maryann Okwegba",
                _id: "678c65de692c5f6ca81f802a",
                image: "",
                color: "#FF0090",
                children: [
                  {
                    name: "Ugochukwu Okwegba",
                    _id: uuidv4(),
                    image: "",
                    color: "#FF0090",
                    children: [],
                  },
                ],
              },
              {
                name: "Ifeoma Nwankwo",
                _id: "678c665b692c5f6ca81f8032",
                image: "",
                color: "#FF0090",
                children: [
                  {
                    name: "Ogochukwu Nwankwo",
                    _id: uuidv4(),
                    image: "",
                    color: "#FF0090",
                    children: [],
                  },
                  {
                    name: "Favour Nwankwo",
                    _id: uuidv4(),
                    image: "",
                    color: "#FF0090",
                    children: [],
                  },
                  {
                    name: "Judith Nwankwo",
                    _id: uuidv4(),
                    image: "",
                    color: "#FF0090",
                    children: [],
                  },
                  {
                    name: "Juliet Nwankwo",
                    _id: uuidv4(),
                    image: "",
                    color: "#FF0090",
                    children: [],
                  },
                  {
                    name: "Wilfred Nwankwo",
                    _id: uuidv4(),
                    image: "",
                    color: "#FF0090",
                    children: [],
                  },
                ],
              },
              {
                name: "Nnamdi Ike",
                _id: uuidv4(),
                image: "",
                color: "#FF0090",
                children: [],
              },
              {
                name: "Nwabueze Ike",
                _id: uuidv4(),
                image: "",
                color: "#FF0090",
                children: [],
              },
              {
                name: "Irene Dike",
                _id: "678c669e692c5f6ca81f8038",
                image: "",
                color: "#FF0090",
                children: [
                  {
                    name: "Ifeanyi Dike",
                    _id: uuidv4(),
                    image: "",
                    color: "#FF0090",
                    children: [],
                  },
                  {
                    name: "Chukwuebuka Dike",
                    _id: uuidv4(),
                    image: "",
                    color: "#FF0090",
                    children: [],
                  },
                  {
                    name: "Peter Dike",
                    _id: uuidv4(),
                    image: "",
                    color: "#FF0090",
                    children: [],
                  },
                ],
              },
              {
                name: "Bartholomew Ike",
                _id: "678c6531692c5f6ca81f8020",
                image: "",
                color: "#FF0090",
                children: [],
              },
            ],
          },
        ],
      },

      // Ayagha Okafor Egbochue (Nee omile)
      {
        name: "Ayagha Okafor Egbochue",
        _id: "678ba895f0da3723bf621634",
        image: "",
        color: "#9400D3",
        children: [
          {
            name: "Vincent Okafor",
            _id: "678c5c31692c5f6ca81f7fc2",
            image: "",
            color: "#9400D3",
            children: [
              {
                name: "Ojukwu Okafor",
                _id: uuidv4(),
                image: "",
                color: "#9400D3",
                children: [],
              },
              {
                name: "Ngozi Osafomwan",
                _id: "678c5ca6692c5f6ca81f7fc7",
                image: "",
                color: "#9400D3",
                children: [
                  {
                    name: "Adesuwa Osafomwan",
                    _id: uuidv4(),
                    image: "",
                    color: "#9400D3",
                    children: [],
                  },
                  {
                    name: "Eyichukwu Osafomwan",
                    _id: uuidv4(),
                    image: "",
                    color: "#9400D3",
                    children: [],
                  },
                ],
              },
              {
                name: "Uche Okafor",
                _id: uuidv4(),
                image: "",
                color: "#9400D3",
                children: [],
              },
              {
                name: "Chike Okafor",
                _id: uuidv4(),
                image: "",
                color: "#9400D3",
                children: [],
              },
              {
                name: "Ebelle Okafor",
                _id: uuidv4(),
                image: "",
                color: "#9400D3",
                children: [],
              },
              {
                name: "Ifeoma Okafor",
                _id: uuidv4(),
                image: "",
                color: "#9400D3",
                children: [],
              },
            ],
          },
          {
            name: "Apolonia Okafor",
            _id: uuidv4(),
            image: "",
            color: "#9400D3",
            children: [],
          },
        ],
      },

      // Roselin Udumelue Anyaeche (Nee omile)
      {
        name: "Roselin Udumelue Anyaeche",
        _id: "678cf5c9e8614fb5b9e4232f",
        image: "",
        color: "#FF4F00",
        children: [
          {
            name: "Chidozie Anyaeche",
            _id: "678cf5c9e8614fb5b9e4232f",
            image: "",
            color: "#FF4F00",
            children: [
              {
                name: "Uju Anyaeche",
                _id: uuidv4(),
                image: "",
                color: "#FF4F00",
                children: [],
              },
              {
                name: "Ijeoma Anyaeche",
                _id: uuidv4(),
                image: "",
                color: "#FF4F00",
                children: [],
              },
              {
                name: "Chukwuebuka Anyaeche",
                _id: uuidv4(),
                image: "",
                color: "#FF4F00",
                children: [],
              },
              {
                name: "Nkiruka Anyaeche",
                _id: uuidv4(),
                image: "",
                color: "#FF4F00",
                children: [],
              },
              {
                name: "Chukwubuikem Anyaeche",
                _id: uuidv4(),
                image: "",
                color: "#FF4F00",
                children: [],
              },
            ],
          },

          {
            name: "Gabriel Anyaeche",
            _id: "678cf6b7e8614fb5b9e4233f",
            image: "",
            color: "#FF4F00",
            children: [
              {
                name: "Ebube Anyaeche",
                _id: uuidv4(),
                image: "",
                color: "#FF4F00",
                children: [],
              },
              {
                name: "Chiemerie Anyaeche",
                _id: uuidv4(),
                image: "",
                color: "#FF4F00",
                children: [],
              },
              {
                name: "Reginald Anyaeche",
                _id: uuidv4(),
                image: "",
                color: "#FF4F00",
                children: [],
              },
              {
                name: "Francis Anyaeche",
                _id: uuidv4(),
                image: "",
                color: "#FF4F00",
                children: [],
              },
              {
                name: "Ogechukwu Anyaeche",
                _id: uuidv4(),
                image: "",
                color: "#FF4F00",
                children: [],
              },
            ],
          },
          {
            name: "Ann Omenilidike",
            _id: uuidv4(),
            image: "",
            color: "#FF4F00",
            children: [],
          },
          {
            name: "Apolonia Nwajugo",
            _id: "678cf738e8614fb5b9e42347",
            image: "",
            color: "#FF4F00",
            children: [],
          },
          {
            name: "Jude Anyaeche",
            _id: "678cf784e8614fb5b9e4234e",
            image: "",
            color: "#FF4F00",
            children: [
              {
                name: "Jude Anyaeche",
                _id: uuidv4(),
                image: "",
                color: "#FF4F00",
                children: [],
              },
              {
                name: "Onyeka Anyaeche",
                _id: uuidv4(),
                image: "",
                color: "#FF4F00",
                children: [],
              },
              {
                name: "Too boy Anyaeche",
                _id: uuidv4(),
                image: "",
                color: "#FF4F00",
                children: [],
              },
              {
                name: "Chikwendu Anyaeche",
                _id: uuidv4(),
                image: "",
                color: "#FF4F00",
                children: [],
              },
            ],
          },
          {
            name: "Vincent Anyaeche",
            _id: uuidv4(),
            image: "",
            color: "#FF4F00",
            children: [],
          },
        ],
      },

      // Grace Okuazanwa Akunne (Nee omile)
      {
        name: "Grace Okuazanwa Akunne",
        _id: "678cf871e8614fb5b9e4235a",
        image: "",
        color: "#8C92AC",
        children: [
          {
            name: "Osita Akunne",
            _id: uuidv4(),
            image: "",
            color: "#8C92AC",
            children: [],
          },
          {
            name: "Hyacinth Akunne",
            _id: "678cf926e8614fb5b9e42368",
            image: "",
            color: "#8C92AC",
            children: [
              {
                name: "Odinaka Akunne",
                _id: uuidv4(),
                image: "",
                color: "#8C92AC",
                children: [],
              },

              {
                name: "Eso Akunne",
                _id: uuidv4(),
                image: "",
                color: "#8C92AC",
                children: [],
              },
              {
                name: "Chukwuka Akunne",
                _id: uuidv4(),
                image: "",
                color: "#8C92AC",
                children: [],
              },
              {
                name: "Sheila Akunne",
                _id: uuidv4(),
                image: "",
                color: "#8C92AC",
                children: [],
              },
            ],
          },
          {
            name: "Franca Omeile",
            _id: uuidv4(),
            image: "",
            color: "#8C92AC",
            children: [],
          },
          {
            name: "Nkasi Uketui",
            _id: "678cf9fbe8614fb5b9e4236f",
            image: "",
            color: "#8C92AC",
            children: [
              {
                name: "Pamela Nwankwo",
                _id: "67b2667c1e58b507f6f25da8",
                image: "",
                color: "#8C92AC",
                children: [
                  {
                    name: "Munachimso Nwankwo",
                    _id: uuidv4(),
                    image: "",
                    color: "#8C92AC",
                    children: [],
                  },
                  {
                    name: "Kamsiyochukwu Nwankwo",
                    _id: uuidv4(),
                    image: "",
                    color: "#8C92AC",
                    children: [],
                  },
                ],
              },
              {
                name: "Emeka Uketui",
                _id: uuidv4(),
                image: "",
                color: "#8C92AC",
                children: [],
              },
              {
                name: "J.J Uketui",
                _id: uuidv4(),
                image: "",
                color: "#8C92AC",
                children: [],
              },
              {
                name: "Afoma Uketui",
                _id: uuidv4(),
                image: "",
                color: "#8C92AC",
                children: [],
              },
            ],
          },
          {
            name: "John Akunne",
            _id: "678cfa6de8614fb5b9e42377",
            image: "",
            color: "#8C92AC",
            children: [
              {
                name: "Nnamelu Akunne",
                _id: uuidv4(),
                image: "",
                color: "#8C92AC",
                children: [],
              },
              {
                name: "Ijeoma Akunne",
                _id: uuidv4(),
                image: "",
                color: "#8C92AC",
                children: [],
              },
              {
                name: "Ogochukwu Akunne",
                _id: uuidv4(),
                image: "",
                color: "#8C92AC",
                children: [],
              },
              {
                name: "Chisom Akunne",
                _id: uuidv4(),
                image: "",
                color: "#8C92AC",
                children: [],
              },
              {
                name: "Chinedum Akunne",
                _id: uuidv4(),
                image: "",
                color: "#8C92AC",
                children: [],
              },
            ],
          },
          {
            name: "Obiageli Ozumba",
            _id: "678cfafbe8614fb5b9e4237e",
            image: "",
            color: "#8C92AC",
            children: [
              {
                name: "Ifechukwu Ozumba",
                _id: uuidv4(),
                image: "",
                color: "#8C92AC",
                children: [],
              },
              {
                name: "Christian Ozumba",
                _id: uuidv4(),
                image: "",
                color: "#8C92AC",
                children: [],
              },
              {
                name: "Joan Ozumba",
                _id: uuidv4(),
                image: "",
                color: "#8C92AC",
                children: [],
              },
              {
                name: "Vanessa Ozumba",
                _id: uuidv4(),
                image: "",
                color: "#8C92AC",
                children: [],
              },
            ],
          },

          //resume Onuorah Akunne
          {
            name: "Onuorah Akunne",
            _id: "678cfba5e8614fb5b9e42384",
            image: "",
            color: "#8C92AC",
            children: [
              {
                name: "Somtochukwu Akunne",
                _id: uuidv4(),
                image: "",
                color: "#8C92AC",
                children: [],
              },
              {
                name: "Tobenna Akunne",
                _id: uuidv4(),
                image: "",
                color: "#8C92AC",
                children: [],
              },
              {
                name: "Kenenna Akunne",
                _id: uuidv4(),
                image: "",
                color: "#8C92AC",
                children: [],
              },
            ],
          },
          {
            name: "Ifeoma Ajagu",
            _id: uuidv4(),
            image: "",
            color: "#8C92AC",
            children: [],
          },
          {
            name: "Chinwe Igwe",
            _id: "678d06057994de84407a3699",
            image: "",
            color: "#8C92AC",
            children: [
              {
                name: "Tobechukwu",
                _id: uuidv4(),
                image: "",
                color: "#8C92AC",
                children: [],
              },
              {
                name: "Emmanuel Igwe",
                _id: uuidv4(),
                image: "",
                color: "#8C92AC",
                children: [],
              },
              {
                name: "Chinwe Igwe",
                _id: uuidv4(),
                image: "",
                color: "#8C92AC",
                children: [],
              },
              {
                name: "Onyinye Igwe",
                _id: uuidv4(),
                image: "",
                color: "#8C92AC",
                children: [],
              },
              {
                name: "Ogochukwu Igwe",
                _id: uuidv4(),
                image: "",
                color: "#8C92AC",
                children: [],
              },
            ],
          },
        ],
      },
    ],
  },
];
